topModule:=motoro301_tb
DEV01:=xc3s500e-pq208-4

CFGmakeRun:=Makefile.run.synopsysVERDI

VERDItb:=motoro301_tb
VERDIrtl:=$(VERDItb)/rtl
VERDIussc:=$(VERDIrtl)/usTop
VERDIucg:=$(VERDIussc)/ucg01
VERDIm3t:=$(VERDIrtl)/m3t
VERDIm3r:=$(VERDIm3t)/r
VERDIm3sg:=$(VERDIm3r)/sg
VERDIm3lgA:=$(VERDIm3r)/lgA
VERDIm3lgB:=$(VERDIm3r)/lgB
VERDIm3lgC:=$(VERDIm3r)/lgC
VERDIm3pwmA:=$(VERDIm3lgA)/pwmSG
VERDIm3pwmB:=$(VERDIm3lgB)/pwmSG
VERDIm3pwmC:=$(VERDIm3lgC)/pwmSG
VERDIm3lcA:=$(VERDIm3lgA)/lCalc
VERDIm3lcB:=$(VERDIm3lgB)/lCalc
VERDIm3lcC:=$(VERDIm3lgC)/lCalc
VERDIm3pcA:=$(VERDIm3lcA)/lcPWMlen

waveAddLine:= wvAddAllSignals -win $$_nWave2

VERICOMdefine:= +define+simulating=1

define waveAddLine

wvRenameGroup   -win $$_nWave2  G1 		TB1
wvAddSignal     -win $$_nWave2  -group {TB1 {/$(VERDItb)/clk}}
wvAddSignal     -win $$_nWave2  -group {TB1 {/$(VERDItb)/nRst}}
wvAddSignal     -win $$_nWave2  -group {TB1 {/$(VERDItb)/tp01}}
wvAddSignal     -win $$_nWave2  -group {TB1 {/$(VERDItb)/tp02}}
wvAddSignal     -win $$_nWave2  -group {TB1 {/$(VERDItb)/led4}}
wvRenameGroup   -win $$_nWave2  G2 		TB2
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/aHP}}
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/aLN}}
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/bHP}}
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/bLN}}
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/cHP}}
wvAddSignal 	-win $$_nWave2  -group {TB2 {/$(VERDItb)/cLN}}

wvRenameGroup 	-win $$_nWave2 	G3 		 RTL1
wvAddSignal 	-win $$_nWave2 	-group 	{RTL1 {/$(VERDIrtl)/clk50mhz}}
wvAddSignal 	-win $$_nWave2 	-group 	{RTL1 {/$(VERDIrtl)/clkM3}}

wvRenameGroup 	-win $$_nWave2 	G4 		 M3real1
wvAddSignal 	-win $$_nWave2 	-group 	{M3real1 {/$(VERDIm3r)/m3forceStop}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real1 {/$(VERDIm3r)/m3invRotate}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real1 {/$(VERDIm3r)/clk}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real1 {/$(VERDIm3r)/nRst}}

wvRenameGroup 	-win $$_nWave2 	G5 		 M3st1
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3stepA}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3stepB}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3stepC}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3cnt}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/roundCNT}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3r_stepCNT_speedSET}}
wvSetRadix 		-format UDec {(M3st1 1) (M3st1 2) (M3st1 3) (M3st1 4) (M3st1 5) (M3st1 6)}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3start}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3start_up1}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3freqINC}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3freqDEC}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st1 {/$(VERDIm3sg)/m3start_clked1}}

wvRenameGroup 	-win $$_nWave2 	G6 		 M3st2
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgA)/lgStep}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgA)/lgEE}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgB)/lgEE}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgC)/lgEE}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3pwmA)/pwm}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgA)/lgH1_L0}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgB)/lgH1_L0}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgC)/lgH1_L0}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgA)/lgForceLow}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgB)/lgForceLow}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3st2 {/$(VERDIm3lgC)/lgForceLow}}
wvSetRadix 		-format UDec {(M3st2 1)}

wvRenameGroup   -win $$_nWave2  G7 		TB3
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/aHP}}
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/aLN}}
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/bHP}}
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/bLN}}
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/cHP}}
wvAddSignal 	-win $$_nWave2  -group {TB3 {/$(VERDItb)/cLN}}


wvRenameGroup 	-win $$_nWave2 	G8 		 M3real2
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/aHp}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/bHp}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/cHp}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/aLp}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/bLp}}
wvAddSignal 	-win $$_nWave2 	-group 	{M3real2 {/$(VERDIm3r)/cLp}}

wvRenameGroup 	-win $$_nWave2 	G9		pwmAnalyze
wvAddSignal 	-win $$_nWave2 	-group 	{pwmAnalyze {/$(VERDIm3pwmA)/pwm}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwmAnalyze {/$(VERDIm3r)/aHp}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwmAnalyze {/$(VERDIm3r)/aLp}}
wvAddSignal 	-win $$_nWave2  -group 	{pwmAnalyze {/$(VERDItb)/aHP}}
wvAddSignal 	-win $$_nWave2  -group 	{pwmAnalyze {/$(VERDItb)/aLN}}
wvAddSignal 	-win $$_nWave2  -group 	{pwmAnalyze {/$(VERDItb)/bHP}}
wvAddSignal 	-win $$_nWave2  -group 	{pwmAnalyze {/$(VERDItb)/bLN}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwmAnalyze {/$(VERDIm3r)/bHp}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwmAnalyze {/$(VERDIm3r)/bLp}}

wvRenameGroup 	-win $$_nWave2 	G10 		 pwm1
wvAddSignal 	-win $$_nWave2 	-group 	{pwm1 {/$(VERDIm3pwmA)/pwm}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwm1 {/$(VERDIm3pwmA)/pwmCNTreload}}
wvAddSignal 	-win $$_nWave2 	-group 	{pwm1 {/$(VERDIm3pwmA)/pwmCNT}}
wvSetRadix 		-format UDec {(pwm1 2) (pwm1 3) }

wvRenameGroup 	-win $$_nWave2 	G11 		 lCalc
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/m3r_power_percent}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/m3r_stepCNT_speedSET}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/m3r_pwmLenWant}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/m3r_pwmMinMask}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/lcStep}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/slLen}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/pwmPOS1}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/pwmPOS2}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/pwmPOS9}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/pwmNow1}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/pwmNow9}}
wvAddSignal     -win $$_nWave2  -group 	{lCalc {/$(VERDIm3pcA)/plLen}}
wvSetRadix 		-format UDec {(lCalc 1) (lCalc 2) (lCalc 3) (lCalc 4) (lCalc 5) (lCalc 6) (lCalc 7) (lCalc 8) (lCalc 9)(lCalc 10)(lCalc 11)(lCalc 12)}

wvRenameGroup 	-win $$_nWave2 	G12 		 UStop
wvAddSignal     -win $$_nWave2  -group {UStop {/$(VERDIussc)/uTx}}
wvAddSignal     -win $$_nWave2  -group {UStop {/$(VERDIussc)/clkUtx}}
wvAddSignal     -win $$_nWave2  -group {UStop {/$(VERDIucg)/cnt}}
wvSetRadix 		-format UDec {(UStop 3)}

endef

